services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: coopcredit-db
    hostname: db
    environment:
      POSTGRES_DB: coopcredit
      POSTGRES_USER: coopcredit
      POSTGRES_PASSWORD: coopcredit123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U coopcredit -d coopcredit" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coopcredit-network

  # Risk Central Mock Service
  risk-central:
    build: ./risk-central-mock-service
    container_name: risk-central-mock
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coopcredit-network

  # Credit Application Service
  credit-service:
    build: ./credit-application-service
    container_name: credit-application-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://coopcredit-db:5432/coopcredit
      SPRING_DATASOURCE_USERNAME: coopcredit
      SPRING_DATASOURCE_PASSWORD: coopcredit123
      APP_RISK-SERVICE_URL: http://risk-central-mock:8081
      APP_JWT_SECRET: mySecretKeyForJWTThatIsAtLeast256BitsLongForHS256AlgorithmUsedInProduction
    depends_on:
      db:
        condition: service_healthy
      risk-central:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - coopcredit-network

volumes:
  postgres_data:


networks:
  coopcredit-network:
    driver: bridge
